name: Stock Biz Automation

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  telegram-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Stock Biz Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py

      - name: Commit updated data
        run: |
          git config --global user.name "Stock Biz Bot"
          git config --global user.email "bot@stockbiz.in"

          git add data/last_news.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update last_news.json"
            git push origin main
          fi
          
